### ISSUE TITLE
Fix instructions for loading word list in Hangman.

### ISSUE THREAD

**Issue by wortzmanb** [TEALS-IntroCS/introduction-to-computer-science-principles#15]
Now requires an extra step to split file into a list.

**Comment by BossJ** [comment]
Can someone point me to where the Hangman file is? Fix would be along the lines of: In order to split your .txt file into a list, use Snap!'s split function and set your delimiter to the appropriate break point (e.g. delimiter of '!' on Split!Me becomes a list of Split, Me).

**Comment by kenneychan** [comment]
Hi Julian,

The projects are located under the "Projects" folder and then "Projects
word".  I think the one you're looking for is "Project 4: Hangman.docx":
https://github.com/TEALS-IntroCS/introduction-to-computer-science-principles/tree/master/Projects/Projects%20Word

**Comment by BossJ** [comment]
I can change 2, Implementation details, to something along the lines of : 
i.	You will be provided a file with a list of words from which the secret word should be chosen for each game. You will be shown in class how to import this file into your program’s list. At the start of each game, a word should be randomly chosen from this list to be used as the secret word. The secret word must be chosen randomly, and must be a word in the list.
I don't necessarily think that this is what you wanted by this issue. I'm not really sure where you'd like to add in splitting the file.

**Comment by smeredith** [comment]
Is importing the word list really important to the lesson? Yes it makes for a more interesting game, but it's a distraction and the lesson would work just as well with a small hard-coded list of words in a list initializer. I might just teach it that way and maybe keep the word list for any advanced student who finish early.

**Comment by wortzmanb** [comment]
@BossJ We should add step-by-step instructions into the lesson plan to explain to teachers how to import the word list (so they can show their students).  See Clair's response here: https://piazza.com/class/ipydv5suhrw56c?cid=62

**Comment by wortzmanb** [comment]
@smeredith You could certainly write the program with a small word list, but in addition to making the game more interesting, using the larger word list discourages students from hard-coding in things that are specific to their word list (like lengths of words).  With a shorter list, some students might try to do something like:

  if (random word == word1)
     length of word = 5
  else if (random word == word2)
     length of word = 4
  else if (random word == word3)
     length of word = 5

where they hard-code how long each word is rather than calculating it.  A longer list makes sure they don't do this.

Importing the list is a one-time operation that can be done with the teacher when the project is introduced, so it shouldn't distract too much.  It usually takes about 3 minutes of class and then everyone has it and it's done.  I think it's worth it.

**Comment by smeredith** [comment]
OK. Then step-by-step instructions on the handout would be best.

**Comment by wortzmanb** [comment]
@smeredith Yup, that's the plan.  :-)

**Comment by BossJ** [comment]
Added step-by-step instructions and an image -- feel free to check it out before closing the issue!
