### ISSUE TITLE
Link to Kaleidoscope in Lab 1.1 is broken

### ISSUE THREAD

**Issue by wortzmanb** [TEALS-IntroCS/introduction-to-computer-science-principles#17]
Extra characters on the end of the TinyUrl.

**Comment by TEALS-IntroCS** [comment]
Can you be more specific. The link I see in the lab 1.1 web page is working: http://tinyurl.com/SNAPKaleidoDraw

Which file contains the broken link? and what is the broken version?

**Comment by BossJ** [comment]
All links in Lab 1.1 work.
