### ISSUE TITLE
Lesson 4.1 Street Writing example is confusing

### ISSUE THREAD

**Issue by TEALS-IntroCS** [TEALS-IntroCS/introduction-to-computer-science-principles#4]
https://piazza.com/class/iaqx9wdtp1t7fj?cid=179

**Comment by BossJ** [comment]
Edited, ready for review.

**Comment by smeredith** [comment]
I don't get lesson 4.1 at all. I don't know how I would teach this.

**Comment by BossJ** [comment]
I was clearing it up from the original Street Writing example which was even more confusing; I changed the topic from Pokemon Go to discoveries in our Solar System, let me know if that helped.

**Comment by smeredith** [comment]
Yes, it makes sense now. Are we only storing a single string (the name) per discovery?

**Comment by BossJ** [comment]
Yes. We're trying to go over list implementation; the students will quickly realize that adding additional strings onto their larger string becomes unmanageable and they need a more dynamic way to store their variables. Feel free to propose edits that you think would make the instructions more clear!
